--Millennium Shield (DOR)
--scripted by GameMaster(GM)
function c511005657.initial_effect(c)
	c:EnableReviveLimit()
	--Def up
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetRange(LOCATION_MZONE)
	e1:SetTargetRange(LOCATION_MZONE,0)
	e1:SetCode(EFFECT_UPDATE_DEFENSE)
	e1:SetTarget(aux.TargetBoolFunction(Card.IsFaceup))
	e1:SetCondition(function(e) return e:GetHandler():IsDefensePos() end)
	e1:SetValue(1000)
	c:RegisterEffect(e1)
end
